### ISSUE TITLE
expose internals of Control.Effect.Conc

### ISSUE THREAD

**Issue by amesgen** [KingoftheHomeless/in-other-words#12]
What about exporting the constructor of `Conc` and/or 

```haskell
unliftConc :: Eff Conc m => ((forall x. m x -> IO x) -> IO a) -> m a
```

from e.g. `Control.Effect.Internal.Conc` in order to be able to use other methods in the style of `Control.Concurrent.Async`, e.g. from [`UnliftIO.Async`](https://hackage.haskell.org/package/unliftio-0.2.14/docs/UnliftIO-Async.html#g:9)?

**Comment by KingoftheHomeless** [comment]
I've actually already done this, I just haven't pushed up a commit for it yet. I'll close this once I do.

**Comment by KingoftheHomeless** [comment]
Wait, I already did, as part of 7c5bb63bcde70d13382db61525b1d562f1fe16a4. It's just waiting for a release, which I've been putting off, but will now commit to releasing during the week..

**Comment by amesgen** [comment]
Thanks for the quick update, should have checked `master` before opening this.

**Comment by KingoftheHomeless** [comment]
`0.2.0.0` is out now.
